// Do not edit. This file is machine generated by the Resource DLL Wizard.

library Project1;

{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit3.dfm}
{ITE} {RCFileType} {Project1_DRC.rc}

{$R 'Unit1.dfm' 'Form1:TForm'}
{$R 'Unit3.dfm' 'Form3:TForm'}
{$R 'Project1_DRC.res' 'Project1_DRC.rc'}

{$E HRV}

begin
end.
